apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myapp-replicaset
  type: front-end
spec:
  template:
    metadata:
      name: myapp-prod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  #Selectors are useful for selecting a set of Pods based Pod definition 
  selector:
    matchLabels:
      type: front-end
    
